service: base-lambda-typescript

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  memorySize: 128



functions:
  hello:
    handler: dist/hello.handler
    events:
      - http:
          path: hello
          method: GET
          cors: true

proxy:
   secureendpoint: false          
